version: "3.7"
services:
  db:
    environment:
      MYSQL_DATABASE: example
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db-password
    image: mariadb:10.6.4-focal
    restart: always
    secrets:
      - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - spring-mysql
  backend:
    build:
      context: backend
      target: development
    environment:
      MYSQL_HOST: db
    networks:
      - react-spring
      - spring-mysql
    depends_on:
      - db
    restart: on-failure:5
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  frontend:
    build:
      context: frontend
      target: development
    ports:
      - 3000:3000
    networks:
      - react-spring
    depends_on:
      - backend
volumes:
  db-data: {}
secrets:
  db-password:
    file: db/password.txt
networks:
  react-spring: {}
  spring-mysql: {}
